import axios from "axios";

const axiosInstance = axios.create();

axiosInstance.interceptors.request.use(
    config => {
        const token = `eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJQcG1kVjM4bTNEVXZ1LVRNU1NWWWhQN3FtOVBUcWV6NERXX056TlNvMUVNIn0.eyJleHAiOjE2NTI3OTU5NTQsImlhdCI6MTY1Mjc1OTk1NCwianRpIjoiYTRlMjVjNWItYWM3Ny00MDAzLTg5MTYtMmE5MGUyYzdhN2E2IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDI0L2F1dGgvcmVhbG1zL3BtcCIsImF1ZCI6InJlYWxtLW1hbmFnZW1lbnQiLCJzdWIiOiI3ZjlkMWRmYy01OTNmLTQ5MGMtYjhkMy1mYTQyMDAwNWQ1MjciLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJwbXBhcHAiLCJzZXNzaW9uX3N0YXRlIjoiNzI1ZGI3MzEtN2ZiMi00MjY5LWI0MGEtMWVjZmMwOThiYmZhIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwOi8vbG9jYWxob3N0OjgwODAiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImFkbWluIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsicmVhbG0tbWFuYWdlbWVudCI6eyJyb2xlcyI6WyJtYW5hZ2UtZXZlbnRzIiwibWFuYWdlLXJlYWxtIiwibWFuYWdlLWNsaWVudHMiXX19LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwic2lkIjoiNzI1ZGI3MzEtN2ZiMi00MjY5LWI0MGEtMWVjZmMwOThiYmZhIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJzaGFkaSBhbGRhYmJhcyIsInByZWZlcnJlZF91c2VybmFtZSI6InNoYWRpYWxkYWJiYXMiLCJnaXZlbl9uYW1lIjoic2hhZGkiLCJmYW1pbHlfbmFtZSI6ImFsZGFiYmFzIiwiZW1haWwiOiJkYWJiYXNmaXJzdEBnbWFpbC5jb20ifQ.L-jG1ltNVh7XewAuMPqEC43X_NtEbwwmD_FucKVm0pmb_27LTtJkyGRGQe2vjeTdOv4I9R8dqaLxLFDPB9rsftBXKs1CzYzpV6dIGzcLLkNeXplka6K_bPAGPeDNlnSWuD0YjzdZCdMtB2m1LflF18BIhmITVBeaYXHnLyAeKSU-5zFKxn5UyKEBMokGPO8mOmsE11Qg0S9LZ74tZd5thiOlIjh_hgzErA8h_bAAu5S3k9RJk9m3ucxpC34w6cD9NyH-T7MG7E159OJi-DB_cp433LWeIld3_p4d4rvUBJbxRnIXuZfe7PCQ0HHg2eOLzY-ywZcEwT5t7b2_I8mL1A
        `;
        config.headers['Authorization'] = 'Bearer ' + token;
        return config;
    }, error => {
        Promise.reject(error)
    }
);

axiosInstance.interceptors.response.use((response) => {
    return response
}, function(error) {
    return Promise.reject(error)   
});

export default axiosInstance;