import axios from "axios";

const axiosInstance = axios.create();

axiosInstance.interceptors.request.use(
    config => {
        const token = `eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJZTDJic0xMb0h5QkdraHp0amRaNkJsbkMzSDRfbHd3ZXl3WndlbkV1X3pFIn0.eyJleHAiOjE2NTI4NTI0MTUsImlhdCI6MTY1MjgxNjQxNSwianRpIjoiMjhkNDQyZmQtMDVjMC00MmJlLTgxZjctNDc0NjZlMDAwNTFmIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDI0L2F1dGgvcmVhbG1zL3BtcCIsImF1ZCI6WyJyZWFsbS1tYW5hZ2VtZW50IiwiYWNjb3VudCJdLCJzdWIiOiI0ZDJkMzdkNy0wYTJmLTQ2MGQtYTA4Yi1lNTYyZjY0NzJhZmYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJwbXBhcHAiLCJzZXNzaW9uX3N0YXRlIjoiNjI4ZjJmYzQtNDhhMi00YjZhLTk3NmMtOTczNzkyYjZmZGU3IiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwOi8vbG9jYWxob3N0OjgwODAiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtcG1wIiwibGFuZGxvYXJkIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsicmVhbG0tbWFuYWdlbWVudCI6eyJyb2xlcyI6WyJtYW5hZ2UtZXZlbnRzIiwibWFuYWdlLXJlYWxtIiwibWFuYWdlLWNsaWVudHMiXX0sInBtcGFwcCI6eyJyb2xlcyI6WyJsYW5kbG9hcmQiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJzaWQiOiI2MjhmMmZjNC00OGEyLTRiNmEtOTc2Yy05NzM3OTJiNmZkZTciLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6Ik1lcmEgTWVyYSIsInByZWZlcnJlZF91c2VybmFtZSI6Im1lcmVzYSIsImdpdmVuX25hbWUiOiJNZXJhIiwiZmFtaWx5X25hbWUiOiJNZXJhIiwiZW1haWwiOiJtZXJhQGdtYWlsLmNvbSJ9.FN7FEcupIEPAgKqudcKcxRUnrlsk680_5cBaAmtB926uszPcpwOuANItEdrg8ZgHs1mkpUiE_NcA0neFACbCwrRHGW9LBwlC4_b0y7uprdNmbrDoZKUL8zX_EPxGL5KZ7C8ViZG92kW6i-pvt_ejBzQrCC4J6hYu9WX93dZmcFoQ7qWgm-Rn-O2gbIm64jtKCvz0EgDRfrTYOAx5BGNrgcsMEuIeQ3wcCoia2_ROwQ4Epk7RvGEpfvtosZ_Au6s_mFj6jaTIuCLPguVuV_-FR661zF8LNrRBcbQmt1y6_hFLni8glHs0r8MrJbmNTRtlcx9o4W8-jX768c2KuZT1nQ`;
        config.headers['Authorization'] = 'Bearer ' + token;
        return config;
    }, error => {
        Promise.reject(error)
    }
);

axiosInstance.interceptors.response.use((response) => {
    return response
}, function(error) {
    return Promise.reject(error)   
});

export default axiosInstance;